package ventanas;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static ventanas.PaginaInicio.LblUser;
import static ventanas.TablaInc.CmbVentanas;
import static ventanas.TablaInc.LblPrivilegios1;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblNick = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TxtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(56, 47, 128));

        LblNick.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        BtnLogin.setText("Entrar");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        BtnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnLoginKeyPressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga.png"))); // NOI18N

        TxtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContraseñaActionPerformed(evt);
            }
        });
        TxtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtContraseñaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(BtnLogin))
                    .addComponent(LblNick, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblNick)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLogin)
                    .addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void TxtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContraseñaActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
       
    String LocalUsuario = LblUser.getText().trim();
        
        System.out.println(LocalUsuario);
        if(!TxtContraseña.getText().equals("")) {
        try{
             Connection cn = DriverManager.getConnection("jdbc:mysql://Localhost:3306/incidenciasdb", "root", "");
         
            PreparedStatement pst = cn.prepareStatement("select * from usuarios where Usuario = ?" );
            pst.setString(1, LocalUsuario);
            
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
            if(LocalUsuario.equals(rs.getString("Usuario")) && TxtContraseña.getText().equals(rs.getString("Contraseña")) && rs.getString("Permisos").equals("Usuario")){
             JOptionPane.showMessageDialog(null, "Bienvenido/a, " + rs.getString("Usuario"));
             TablaInc tab = new TablaInc();
      tab.setVisible(true);
      LblUser.setText("");
      dispose();
         }else if(LocalUsuario.equals(rs.getString("Usuario")) && TxtContraseña.getText().equals(rs.getString("Contraseña")) && rs.getString("Permisos").equals("Administrador")){
             JOptionPane.showMessageDialog(null, "Bienvenido/a, " + rs.getString("Usuario"));
             
             TablaInc tab = new TablaInc();
             
      tab.setVisible(true);
      LblPrivilegios1.setText("Administrador");
      CmbVentanas.addItem("Registro de usuarios");
      LblUser.setText("");
      dispose();
      
         }
         
            }else if(!LocalUsuario.equals(rs.getString("Usuario")) || !TxtContraseña.getText().equals(rs.getString("Contraseña"))){
             JOptionPane.showMessageDialog(null, "error, contraseña incorrecta");  
            }
         }catch(Exception E){
             JOptionPane.showMessageDialog(null, E/*"error, contraseña incorrecta"*/);
         }
        }else{
            JOptionPane.showMessageDialog(null, "introduce la contraseña");
        }
         
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnLoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLoginKeyPressed

    private void TxtContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtContraseñaKeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER)  {
          
        
    String LocalUsuario = LblUser.getText().trim();
        
        System.out.println(LocalUsuario);
        if(!TxtContraseña.getText().equals("")) {
        try{
             Connection cn = DriverManager.getConnection("jdbc:mysql://Localhost:3306/incidenciasdb", "root", "");
         
            PreparedStatement pst = cn.prepareStatement("select * from usuarios where Usuario = ?" );
            pst.setString(1, LocalUsuario);
            
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
            if(LocalUsuario.equals(rs.getString("Usuario")) && TxtContraseña.getText().equals(rs.getString("Contraseña")) && rs.getString("Permisos").equals("Usuario")){
             JOptionPane.showMessageDialog(null, "Bienvenido/a, " + rs.getString("Usuario"));
             TablaInc tab = new TablaInc();
      tab.setVisible(true);
      LblUser.setText("");
      dispose();
         }else if(LocalUsuario.equals(rs.getString("Usuario")) && TxtContraseña.getText().equals(rs.getString("Contraseña")) && rs.getString("Permisos").equals("Administrador")){
             JOptionPane.showMessageDialog(null, "Bienvenido/a, " + rs.getString("Usuario"));
             
             TablaInc tab = new TablaInc();
             
      tab.setVisible(true);
      LblPrivilegios1.setText("Administrador");
      CmbVentanas.addItem("Registro de usuarios");
      LblUser.setText("");
      dispose();
      }else{
             JOptionPane.showMessageDialog(null, "error, contraseña incorrecta"); 
         }
         
             
            }
         }catch(Exception E){
             JOptionPane.showMessageDialog(null, E/*"error, contraseña incorrecta"*/);
         }
        }else{
            JOptionPane.showMessageDialog(null, "introduce la contraseña");
        }
}
    }//GEN-LAST:event_TxtContraseñaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    public static javax.swing.JLabel LblNick;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/img/icono.png"));
    }
}
